env:
  global:
    - secure: hBeO80hxmLM49d6+zqQm0gsZ9g0ZzZY57TCHSmaMZQBHxieGEb755/pQdcxi4JHX5MeMRns7T3HpZLSqlngYOracBZJIx90hZk/SXCHifSMUTzKV6PaBXlYPmU253M52M+gF0CEjXM0wZyTKfxPjXlOLC71y3IeZl6+rYzN2kIH2ydqVQqhb2QJbLsN8/xietUJLsCtew6pSmXLfiePU32yNf8JRh+HVcXuTywfaCQ1dsiNoG1VHetoLJaY9ZDznctl1FUiZQSQitciBe+QLYYkc6Rx9G1anffZrMdMFCsR0ya39tCfvZpye4KEjoOZ3roVvC8+X7PZoxjFXe4dtrBNvqze5tzquN5UAg0vKfhD9Gwi5ehCKoCKwUqdyo8f00QJ43RjgOi39YySUL9x7/uiMGlnXP17su2sYYPNzcRj8+b3on0yWzHJDJAHbn0Rrp2PIpc0i4xTPmqGJptLqJ6RKVkdc7r7H909YvpAntJAYcviWSE5C+XLpaUgOICdU0BlXs9DKdg7VHhbgAGonABZb+GXA2+nDrvx0K31XG9j9+Sy7TTTGqgeZcfvXcUUkvTb5bEMf09WG+ojDVZF7CKc75rSjlkYhoRXj9jt17FVEnoqSOqmnM1kjb8KzJSJy8pO9yoWEpQSaYHQsEeyX80+9uA6t7vnJkIzNY8DBQQE=
language: node_js
sudo: required
services:
  - docker
node_js:
  - "lts/carbon"
jobs:
  include:
    - stage: build
      script:
        - npm install
        # - npm run deploy